### ISSUE TITLE
Angular 8, support

### ISSUE THREAD

**Issue by videmort** [ionic-team/angular-toolkit#158]
This library is not working with lastest angular 8 versions.
To repoduce just update the angular libraries in the package.json to 8.0.2

Could not find the implementation for builder @ionic/angular-toolkit:cordova-build
Error: Could not find the implementation for builder @ionic/angular-toolkit:cordova-build

**Comment by mhartington** [comment]
Hi there, Angular 8 support is part of the 2.0, as noted in our changelog.

https://github.com/ionic-team/angular-toolkit/blob/master/CHANGELOG.md

We have an official upgrade guide created here

https://docs.google.com/document/d/1QOpQeDifPSg6F9WycDLcbQnpqjN96ew-Ap0_CB7CcCQ/edit#
