### ISSUE TITLE
Data path ".builders['cordova-build']" should have required property 'class'

### ISSUE THREAD

**Issue by lilian131** [ionic-team/angular-toolkit#166]
this happen on ios and android after updating to ionic cli v5 
and installing cordova-res native-run
testing on emulator

**ionic info**

Ionic:

   Ionic CLI                     : 5.2.1 (/Users/abdelhakim/.nvm/versions/node/v10.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.800.6
   @angular-devkit/schematics    : 8.1.0
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.0.0-beta.25
   @capacitor/core : 1.0.0-beta.25

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.5.2
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (/Users/abdelhakim/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.1 (/Users/abdelhakim/.nvm/versions/node/v10.15.1/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by Noaber** [comment]
I am running into the same issue

**Comment by lilian131** [comment]
@Noaber  update **@angular/cli to ~8.1.0** fix it !
look this link: [https://update.angular.io/#7.2:8.0](url)

**Comment by Noaber** [comment]
@lilian131, thanks tried that but getting a 

`Cannot find module '@angular/compiler-cli/ngcc'`

Could you please your package.json ?

**Comment by lilian131** [comment]
yes @Noaber  it was a bit painfully to update here it is  
```
{
  "name": "almamlaka-app-v4",
  "version": "2.0.5",
  "author": "Ionic Framework",
  "homepage": "https://almamlakasweets.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:development:ios": "ionic cordova build ios",
    "build:development:android": "ionic cordova build android",
    "build:production:ios": "ionic cordova build ios --prod --release",
    "build:production:android": "ionic cordova build android --prod --release"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.1.0",
    "@angular/common": "^8.1.0",
    "@angular/core": "^8.1.0",
    "@angular/forms": "^8.1.0",
    "@angular/platform-browser": "^8.1.0",
    "@angular/platform-browser-dynamic": "^8.1.0",
    "@angular/router": "^8.1.0",
    "@capacitor/android": "^1.1.0",
    "@capacitor/cli": "1.0.0-beta.25",
    "@capacitor/core": "1.0.0-beta.25",
    "@capacitor/ios": "^1.1.0",
    "@ionic-native/app-version": "^5.9.0",
    "@ionic-native/core": "^5.9.0",
    "@ionic-native/diagnostic": "^5.9.0",
    "@ionic-native/email-composer": "^5.9.0",
    "@ionic-native/geolocation": "^5.9.0",
    "@ionic-native/google-maps": "^5.0.0-beta.27",
    "@ionic-native/in-app-review": "^5.9.0",
    "@ionic-native/launch-navigator": "^5.9.0",
    "@ionic-native/market": "^5.9.0",
    "@ionic-native/onesignal": "^5.9.0",
    "@ionic-native/social-sharing": "^5.9.0",
    "@ionic-native/splash-screen": "^5.9.0",
    "@ionic-native/status-bar": "^5.9.0",
    "@ionic/angular": "^4.6.0",
    "@ionic/core": "^4.6.0",
    "@ionic/pro": "2.0.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@prototypeberlin/cordova-plugin-accountkit": "git+https://github.com/prototype-berlin/cordova-plugin-accountkit.git",
    "cordova-android": "^8.0.0",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-accountkit": "^1.4.0",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-email-composer": "^0.9.2",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googlemaps": "2.6.2",
    "cordova-plugin-ionic-keyboard": "2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-market": "1.2.0",
    "cordova-plugin-splashscreen": "5.0.3",
    "cordova-plugin-statusbar": "2.4.3",
    "cordova-plugin-x-socialsharing": "5.4.7",
    "cordova.plugins.diagnostic": "5.0.0",
    "core-js": "^2.6.9",
    "es6-promise-plugin": "4.2.2",
    "minimatch": "^3.0.4",
    "onesignal-cordova-plugin": "2.4.7",
    "rxjs": "~6.5.2",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^5.0.4",
    "web-animations-js": "^2.3.2",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.800.0",
    "@angular-devkit/build-angular": "~0.801.0",
    "@angular-devkit/core": "~8",
    "@angular-devkit/schematics": "~8",
    "@angular/cli": "~8.1.0",
    "@angular/compiler": "^8.1.0",
    "@angular/compiler-cli": "^8.1.0",
    "@angular/language-service": "^8.1.0",
    "@ionic/angular-toolkit": "^2.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.4.5"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-dialogs": {},
      "cordova-plugin-actionsheet": {},
      "cordova-plugin-googlemaps": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-market": {},
      "cordova.plugins.diagnostic": {},
      "onesignal-cordova-plugin": {},
      "es6-promise-plugin": {},
      "uk.co.workingedge.phonegap.plugin.launchnavigator": {
        "GOOGLE_API_KEY_FOR_ANDROID": "",
        "OKHTTP_VERSION": "3.12.0",
        "LOCATION_USAGE_DESCRIPTION": "This app requires access to your location for navigation purposes"
      },
      "cordova-plugin-add-swift-support": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-email-composer": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-app-version": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-accountkit": {
        "APP_ID": "",
        "APP_NAME": "",
        "CLIENT_TOKEN": "",
        "API_VERSION": "v1.3"
      }
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
```

**Comment by Noaber** [comment]
@lilian131, thank you it's working now!
Needed to update CLI + Core of Angular and set TypeScript from 3.5 to 3.4.5

**Comment by lilian131** [comment]
happy to help

**Comment by pablomaurer** [comment]
- `"@ionic/angular-toolkit": "~1.5.1",` is for angular 7
- `"@ionic/angular-toolkit": "~2.0.0“,` is for angular 8

As long as these versions match it should work.

**Comment by pullatjunaid** [comment]
I have same issue
My package.json

{
  "name": "myapp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.15",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/facebook": "^5.11.0",
    "@ionic-native/google-plus": "^5.12.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "@ionic/storage": "^2.2.0",
    "cordova-android": "7.1.4",
    "cordova-android-support-gradle-release": "^3.0.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-facebook4": "^5.0.0",
    "cordova-plugin-googleplus": "^8.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-sqlite-storage": "^3.2.1",
    "core-js": "^2.5.4",
    "paulstelzer-ionic-angular-toolkit": "^2.0.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "^7.3.9",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.5.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.6.6",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.17.0",
    "typescript": "~3.4.5"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
     
      "cordova-android-support-gradle-release": {}
    },
    "platforms": [
      "android"
    ]
  }
}
Any help will appreciate

**Comment by taahi** [comment]
I Have the same Problem
My package.json

{
  "name": "example",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "run:ios": "ionic cordova run ios --buildFlag='-UseModernBuildSystem=0'  --buildFlag='-allowProvisioningUpdates'",
    "run:ios_real_dev": "ionic cordova run ios --device  -- --buildFlag='-UseModernBuildSystem=0'",
    "run:browser": "ionic cordova run browser -l --live-reload",
    "run:android": "ionic cordova emulate android -l",
    "run:android_real_dev": "ionic cordova run android -l",
    "build:ios:aot": "ionic cordova build ios --aot --minifyjs --minifycss --releas -- --buildFlag='-UseModernBuildSystem=0'",
    "build:browser:aot": "ionic cordova build browser --aot --minifyjs --minifycss --release",
    "build:android:aot": "ionic cordova build android --prod --release"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.1.0",
    "@angular-devkit/build-angular": "^0.803.24",
    "@angular-devkit/build-webpack": "0.803.24",
    "@angular/cli": "^7.3.8",
    "@angular/common": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/http": "7.2.16",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@ionic-native/call-number": "5.20.0",
    "@ionic-native/core": "5.20.0",
    "@ionic-native/dialogs": "5.20.0",
    "@ionic-native/file": "^5.20.0",
    "@ionic-native/file-transfer": "^5.20.0",
    "@ionic-native/geolocation": "5.20.0",
    "@ionic-native/image-picker": "5.20.0",
    "@ionic-native/ionic-webview": "^5.20.0",
    "@ionic-native/launch-navigator": "5.20.0",
    "@ionic-native/native-geocoder": "5.20.0",
    "@ionic-native/native-storage": "^5.20.0",
    "@ionic-native/social-sharing": "5.20.0",
    "@ionic-native/splash-screen": "5.20.0",
    "@ionic-native/status-bar": "5.20.0",
    "@ionic/angular": "^4.11.10",
    "@ionic/storage": "2.2.0",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "@types/jquery": "^3.3.32",
    "acorn": "7.1.0",
    "agm-direction": "0.7.9",
    "balanced-match": "1.0.0",
    "call-number": "1.0.1",
    "color": "3.1.2",
    "cordova-android": "^8.1.0",
    "cordova-browser": "6.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-nativegeocoder": "^3.2.2",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-x-socialsharing": "^5.6.3",
    "core-js": "3.6.4",
    "easyimage": "^3.1.1",
    "es6-promise-plugin": "^4.2.2",
    "hammerjs": "2.0.8",
    "ionic-cache": "4.1.0",
    "ionic-image-loader": "^7.0.0-beta.2",
    "ionic-swipe-all": "2.0.0",
    "leaflet": "^1.6.0",
    "mx.ferreyra.callnumber": "0.0.2",
    "npm": "^6.13.7",
    "rxjs": "~6.5.4",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^5.0.4",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "0.803.24",
    "@angular-devkit/core": "~8.3.24",
    "@angular-devkit/schematics": "^8.3.24",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@ionic/angular-toolkit": "^2.1.2",
    "@types/color": "3.0.1",
    "@types/jasmine": "^3.5.3",
    "@types/jasminewd2": "^2.0.8",
    "@types/js-base64": "2.3.1",
    "@types/leaflet": "^1.5.8",
    "@types/node": "~13.7.0",
    "codelyzer": "~5.2.1",
    "fs-extra": "^8.1.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "~3.1.0",
    "karma-jasmine-html-reporter": "1.5.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.6.2",
    "tslint": "^5.20.1",
    "typescript": "^3.5.3"
  },
  "description": "A Custom Listing App project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-dialogs": {},
      "mx.ferreyra.callnumber": {},
      "uk.co.workingedge.phonegap.plugin.launchnavigator": {
        "GOOGLE_API_KEY_FOR_ANDROID": "AIzaSy-your_key",
        "LOCATION_USAGE_DESCRIPTION": "This app requires access to your location for navigation purposes",
        "OKHTTP_VERSION": "3.12.0"
      },
      "cordova-plugin-telerik-imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-geolocation": {},
      "cordova-plugin-nativegeocoder": {
        "LOCATION_WHEN_IN_USE_DESCRIPTION": "Use geocoder service"
      },
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
      },
      "cordova-plugin-file": {},
      "call-number": {},
      "cordova-plugin-nativestorage": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-add-swift-support": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      }
    },
    "platforms": [
      "browser",
      "android",
      "ios"
    ]
  }
}
