### ISSUE TITLE
Toolkit for Capacior

### ISSUE THREAD

**Issue by matheo** [ionic-team/angular-toolkit#178]
Hi @mhartington!
Is there any chance to get some builders for Ionic + Capacitor instead Cordova?
Is it possible? needed? or we just skip the ionic tooling it to run the App with the Native editor like we have to do while working with Xplat+ Monorepo?
Thanks for the great stuff!

**Comment by mhartington** [comment]
We'll work on the capacitor tooling for angular here 

https://github.com/ionic-team/capacitor-angular-toolkit
