### ISSUE TITLE
No cordova.js added to index.html without "scripts" property in angular.json

### ISSUE THREAD

**Issue by maxtacco** [ionic-team/angular-toolkit#179]
Hi, 
I just spent hours investigating why cordova.js wasn't included in the final index.html of my Ionic project. It looks like after updating to Angular 8 / Ionic toolkit 2.0.0 I have to add "scripts" property to angular.json's  build section even if I don't have any additional scripts to configure.
This is really weird behavior and should be documented or a warning given at least. Better yet Ionic toolkit should be updated to add cordova.js without checking for "scripts" in options.

**Comment by mhartington** [comment]
Hey there! Good catch. It looks like I wrote a check for scripts, but never handled a situation where scripts would be null. Should be an easy fix
