### ISSUE TITLE
ionic g page, cli creates 6 files

### ISSUE THREAD

**Issue by shahramSo** [ionic-team/angular-toolkit#185]
I encountered to an issue when I want to create a page by ionic cli as follows:
 ionic g page list:
then the created pages as follows:
CREATE src/app/list/list-routing.module.ts (339 bytes)
CREATE src/app/list/list.module.ts (458 bytes)
CREATE src/app/list/list.page.html (123 bytes)
CREATE src/app/list/list.page.spec.ts (633 bytes)
CREATE src/app/list/list.page.ts (248 bytes)
CREATE src/app/list/list.page.scss (0 bytes)
UPDATE src/app/app-routing.module.ts (578 bytes)

as you have seen 6 files created!

but when i downgrade @ionic/angular-toolkit : 2.1.1 to 2.0.0  so the issue has been resolved and created files are 5 files as follows:
CREATE src/app/list/list.module.ts (533 bytes)
CREATE src/app/list/list.page.html (123 bytes)
CREATE src/app/list/list.page.spec.ts (677 bytes)
CREATE src/app/list/list.page.ts (248 bytes)
CREATE src/app/list/list.page.scss (0 bytes)
UPDATE src/app/app-routing.module.ts (540 bytes)

I installed latest nodejs and ionic cli as follows:

   Ionic CLI                     : 5.4.13 
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

please check this issue and let me know if you need more info.
Thanks

**Comment by dwieeb** [comment]
The new version creates a separate routing module to be consistent with the Ionic starters and Angular best practices. The commit is here: https://github.com/ionic-team/angular-toolkit/commit/b13b8233c1b693be7a845494b3d98cda2c8fe1da
