### ISSUE TITLE
bug: Angular "ionic g page SomeName --no-module" is broken

### ISSUE THREAD

**Issue by ammulder** [ionic-team/angular-toolkit#249]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Create an app with `ionic start --type=angular my-app blank`
Go to new directory and run: `ionic generate page SomeName --no-module`
Output:
```
> ng generate page SomeName --module=false --project=app
Specified module does not exist
[ERROR] Could not generate page.
```
It does not generate a page

**Expected behavior:**

Expected it to generate a page

**Steps to reproduce:**

See above

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/Users/ammulder/.nvm/versions/node/v12.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.1 (/Users/ammulder/.nvm/versions/node/v12.18.1/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by mhartington** [comment]
There is no `--no-module` option. `--module`  accepts a string, not a boolean. This is working as intended.

**Comment by top1st** [comment]
Why there is no option to create a page only without a module?
