### ISSUE TITLE
File auth does not exist with --module=auth 

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/angular-toolkit#326]
Hi,

`ionic g component modules/auth/pages/sign-up --spec=false --module=auth`

gives this error:

```
ng.cmd generate component modules/auth/pages/sign-up --spec=false --module=auth --project=app
File auth does not exist.
[ERROR] Could not generate component.
```

![1](https://user-images.githubusercontent.com/5206526/93815663-f9c38380-fc73-11ea-85ea-c15628e72864.png)

**Ionic Info**

Ionic:

Ionic CLI : 6.9.2 (C:\Users\Sampath\AppData\Roaming\npm\node_modules@ionic\cli)
Ionic Framework : @ionic/angular 5.3.3
@angular-devkit/build-angular : 0.1001.2
@angular-devkit/schematics : 10.0.8
@angular/cli : 10.1.2
@ionic/angular-toolkit : 2.3.3

Capacitor:

Capacitor CLI : 2.4.1
@capacitor/core : 2.4.1

Utility:

cordova-res : 0.14.0
native-run (update available: 0.3.0) : 0.2.5

System:

NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
npm : 6.12.1
OS : Windows 10

**Comment by mhartington** [comment]
I think the path being passed in with `--module=auth` is incorrect. Can you try `--module=modules/auth` instead?
