### ISSUE TITLE
use ionic in a separate module

### ISSUE THREAD

**Issue by BrainBolder** [ionic-team/angular-toolkit#334]
Hello everyone, I found an interesting problem,
i want to shove ionic in a separate module and load it with lazy loading

@NgModule({
  imports: [
    CommonModule, 
    IonicModule.forRoot(),
    MobileRoutingModule
  ],
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  declarations: [MobileComponent],
  entryComponents: [ MobileComponent ],
})
export class MobileModule {}

the module "MobileModule" is loaded but the components are not displayed properly, an example of display is in the screenshot.
If we add
IonicModule.forRoot (), in the AppModule, then the components are immediately converted normally. Can anyone come across this problem?
![photo_2020-09-27_16-22-55](https://user-images.githubusercontent.com/44431628/94366037-06b1fe00-00de-11eb-882b-2a281f034a8a.jpg)
![photo_2020-09-27_16-23-00](https://user-images.githubusercontent.com/44431628/94366038-074a9480-00de-11eb-9c03-aeffa33f599c.jpg)

**Comment by mhartington** [comment]
Hi there. This is the repo for the ionic/angular-toolkit, a package for helping devs build ionic/angular apps with cordova. Your issue does not seem to be related to this repo. I am going to close the issue.


Please open your issue on the main Ionic repo


http://github.com/ionic-team/ionic-framework
