### ISSUE TITLE
Path problem occurs after updating to angular 11

### ISSUE THREAD

**Issue by UTSOURCE** [ionic-team/angular-toolkit#380]
E:\net\UT.APP>ionic cordova build android
> ng.cmd run app:ionic-cordova-build --platform=android
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/utils'
Require stack:
- E:\net\UT.APP\node_modules\@ionic\angular-toolkit\builders\utils\index.js
- E:\net\UT.APP\node_modules\@ionic\angular-toolkit\builders\cordova-build\index.js
- E:\net\UT.APP\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- E:\net\UT.APP\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- E:\net\UT.APP\node_modules\@angular\cli\models\architect-command.js
- E:\net\UT.APP\node_modules\@angular\cli\commands\run-impl.js
- E:\net\UT.APP\node_modules\@angular-devkit\schematics\tools\export-ref.js
- E:\net\UT.APP\node_modules\@angular-devkit\schematics\tools\index.js
- E:\net\UT.APP\node_modules\@angular\cli\utilities\json-schema.js
- E:\net\UT.APP\node_modules\@angular\cli\models\command-runner.js
- E:\net\UT.APP\node_modules\@angular\cli\lib\cli\index.js
- E:\net\UT.APP\node_modules\@angular\cli\lib\init.js
- E:\net\UT.APP\node_modules\@angular\cli\bin\ng
See "C:\Users\zhang\AppData\Local\Temp\ng-eO8POF\angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 127.

        Re-running this command with the --verbose flag may provide more information.

**Comment by programadoracoriano** [comment]
I have this problem too, waiting for a resolution. The web  works well, but the android build always get that error above. My Week update was delayed because of this.

**Comment by llimz** [comment]
Same here. Web also working but build ios and android is not working with the same error.

**Comment by UTSOURCE** [comment]
> 我也有这个问题，正在等待解决。网络运行良好，但android构建始终会在上面得到该错误。因此，我的周更新被延迟了。



> I have this problem too, waiting for a resolution. The web works well, but the android build always get that error above. My Week update was delayed because of this.

me to

**Comment by J4cku** [comment]
@UTSOURCE @llimz  @programadoracoriano already opened PR for this https://github.com/ionic-team/angular-toolkit/pull/388

**Comment by mhartington** [comment]
This should be fixed with the latest major release, 3.0.0

**Comment by vadimwe** [comment]
+1 Same problem

**Comment by mhartington** [comment]
@vadimwe 

1) update to the latest release, `@ionic/angular-toolkit@3`
2) if you are still having issues, open a *new* issue with more details.
