### ISSUE TITLE
angular update - migration failed: Incompatible peer dependencies found

### ISSUE THREAD

**Issue by luboslav** [ionic-team/angular-toolkit#437]
When trying to update angular version via `ng update @angular/core @angular/cli` I get errors: 

```
Package "@ionic/angular-toolkit" has an incompatible peer dependency to "@angular-devkit/architect" (requires "^0.1100.0", would install "0.1101.0")
Package "@ionic/angular-toolkit" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires "^0.1100.0", would install "0.1101.0")
```

**Comment by fmendoza** [comment]
Just add `--force` as a workaround

**Comment by mhartington** [comment]
Yeah, until the devkit team properly follows semver, this isn't really something that can account for. With their versioning being so different, any npm/yarn semver checks will not satisfy 

https://jubianchi.github.io/semver-check/#/~0.1100.0/0.1101.0

As a temp work around, `--force` should work without issues.

**Comment by luboslav** [comment]
Use of `--force` works, thank you.

**Comment by ASomerN** [comment]
When forcing this change it introduces a breaking change when compiling an ionic app to Android, we get an error fn.bind() is not a function in logcat. Reverting resolves the issue.

**Comment by mhartington** [comment]
@ASomerN That issue actually related to chrome and an angular release, not anything specific to angular toolkit.

https://twitter.com/LPCMedia/status/1352272779014533121

Going to close this as I merged https://github.com/ionic-team/angular-toolkit/commit/e8c5cf96db3ab4f1344df31827f7b9ee05fe9f5a which should address this.

Thank you!

**Comment by MohittPattel** [comment]
> Use of `--force` works, thank you.

This works for me, thanks!
