### ISSUE TITLE
Custom webpack support

### ISSUE THREAD

**Issue by nkprince007** [ionic-team/angular-toolkit#44]
I'm trying to use React with ionic 4 out of the box. I started out with a blank ionic project with 
`ionic start react-test blank --type=angular` and used custom builders to add additional configuration to webpack (for JSX, `babel-preset-react`, etc). 

However, I'm not able to use Cordova that way as it is inject via ionic cli during the build process. This is a request to provide extensibility in the builder `@ionic/angular-toolkit:cordova-serve`.

Reference: https://github.com/ionic-team/ionic/issues/15893#issuecomment-444993307

**Comment by dwieeb** [comment]
If you want to extend the `cordova-serve` builder, just do so. We extend the Angular builders for the dev server:

https://github.com/ionic-team/angular-toolkit/blob/9d65915642b6e9e229a1122e6e2f116039744885/builders/cordova-serve/index.ts#L47

You can also use the builders in other builders:

https://github.com/ionic-team/angular-toolkit/blob/9d65915642b6e9e229a1122e6e2f116039744885/builders/cordova-build/index.ts#L16

The extensibility is largely dictated by the Angular DevKit and tooling maintained by the Angular team. If there's something we're not doing correctly on our end, please let us know. PRs are also welcome.

It goes without saying that Ionic + React isn't at all close to being ready. Apps started with the `--type=angular` flag are going to look very different from apps started with `--type=react`, when it is supported.
