### ISSUE TITLE
npm install fails because of an angular bug

### ISSUE THREAD

**Issue by m8xp0w3r** [ionic-team/angular-toolkit#444]
As discussed [here](https://github.com/angular/angular-cli/issues/19957) angular has some problems with npm7. This is fixed in newest angular versions like `11.2.2`. You are using angular in version `11.1.x`

`Package "@ionic/angular-toolkit" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires "^0.1101.0", would install "0.1102.2").`

This usage causes these warnings in console when running `npm install`:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/38067181/109418224-86aefd80-79c7-11eb-8587-b440bdd28266.png">

Updating these dependencies would be awesome!

UPDATE: This [PR](https://github.com/ionic-team/angular-toolkit/pull/443) probably will fix this issue.

Cheers

**Comment by mhartington** [comment]
Closing as fixed via https://github.com/ionic-team/angular-toolkit/commit/e8c5cf96db3ab4f1344df31827f7b9ee05fe9f5a

**Comment by m8xp0w3r** [comment]
Awesome. Thank you. After some minutes in npm install hell now everything works fine.
