### ISSUE TITLE
Generate page when having @angular-eslint/schematics installed fails

### ISSUE THREAD

**Issue by jesperbjerke** [ionic-team/angular-toolkit#449]
**Description:**
After converting to eslint from tslint following this blogpost: https://ionicframework.com/blog/eslint-for-ionic-angular/
I am no longer able to run `ionic generate page xxx`. It seems like the "page" type is no longer available?

**Steps to Reproduce:**
Have @angular-eslint/schematics installed and run `ionic generate page xxx`

**Output:**
```
$ ionic generate page views/communication/chat/conversation
    > ng generate page views/communication/chat/conversation --project=app
    An unhandled exception occurred: Schematic "page" not found in collection "@angular-eslint/schematics".
```

Running `npx ng g` gives me the following list of available schematics:

```
Available Schematics:
  Collection "@angular-eslint/schematics" (default):
    app-shell
    application
    class
    component
    convert-tslint-to-eslint
    directive
    enum
    guard
    interceptor
    interface
    library
    module
    ng-add
    pipe
    resolver
    service
    service-worker
    web-worker
```

**Comment by juanmafont** [comment]
Same here, ionic 5 updated to angular 11.

**Comment by mhartington** [comment]
Please check your angular.json for the `cli` field.

```
  "cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },
```

It should be set to `@ionic/angular-toolkit`

**Comment by mhartington** [comment]
@jesperbjerke you're issue is that the schematics got changed in your angular.json. in the error message you printed out, it's not calling the ionic/angular-toolkit.

```
An unhandled exception occurred: Schematic "page" not found in collection "@angular-eslint/schematics".
```

How and why that changed, not sure though.

**Comment by juanmafont** [comment]
>  "defaultCollection": "@ionic/angular-toolkit"

Yes, that's the problem.  Thanks.
 
At my angular.json said ->
`"defaultCollection": "@angular-eslint/schematics"`

 Maybe modificated when install eslint as default  and remove tslint

**Comment by alemdg** [comment]
> Please check your angular.json for the `cli` field.
> 
> ```
>   "cli": {
>     "defaultCollection": "@ionic/angular-toolkit"
>   },
> ```
> 
> It should be set to `@ionic/angular-toolkit`

Now I am getting 

 NOT SUPPORTED: keyword "id", use "$id" for schema ID

**Comment by llunardi** [comment]
I am getting the same error after editing the cli as above. Now I see "An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID   "

**Comment by llunardi** [comment]
> 

I am receiving exact same error, did you ever fix?

**Comment by mhartington** [comment]
@llunardi Please open a *new* issue with more details and a sample repo link

**Comment by ddisqq** [comment]
I am seeing the same issue when running:
_**ionic generate page**_

An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
