### ISSUE TITLE
bump cheerio to 1.0.0-rc.10

### ISSUE THREAD

**Issue by chaymankala** [ionic-team/angular-toolkit#458]
There is a High priority npm vulnerability ([Denial of Service](https://npmjs.com/advisories/1754)) in one of cheerio's dependencies, 

Package       │ css-what              
Path              │ @ionic/angular-toolkit > cheerio > css-select > css-what

This can be fixed with cheerio update to latest - 1.0.0-rc.10

**Comment by mhartington** [comment]
This has already been done....but worth noting that npm audit leads to false positives.


https://overreacted.io/npm-audit-broken-by-design/
