### ISSUE TITLE
Angular v13

### ISSUE THREAD

**Issue by hakimio** [ionic-team/angular-toolkit#464]
Library dependencies should be updated to make it compatible with Angular v13.

**Comment by Mendzyy** [comment]
Why want they reply? @hakimio

**Comment by mhartington** [comment]
In progress

**Comment by hakimio** [comment]
@Mendzyy you can try version `5.0.4-testing.4` which supports Angular 13 and seems to be perfectly usable.

**Comment by mhartington** [comment]
Please hold off on the test branch for now. It contains breaking changes.

**Comment by znotdead** [comment]
Any estimates? Thanks!

**Comment by tobika** [comment]
I see t hat angular 13 seems to work with 5.0, so should we downgrade for the time being?
https://github.com/ionic-team/starters/blob/main/angular/base/package.json
