### ISSUE TITLE
Cordova not working with angular-toolkit@6.0.0

### ISSUE THREAD

**Issue by camengadisaputra-dev** [ionic-team/angular-toolkit#466]
It seem like cordova not working with angular-toolkit@6.0.0. I testing with new project when upgrade to version 6 this error appear.

[error] Error: Package "@ionic/angular-toolkit" has no builders defined.

**Comment by neegexmayank** [comment]
![image](https://user-images.githubusercontent.com/49301253/152780621-c2ad773a-77cc-47bb-862c-805d27ac6aa8.png)

have same issue... with version @6.0.0

**Comment by neegexmayank** [comment]
https://ionicframework.com/blog/updates-to-ionic-angular-toolkit/

i think this is the solution. with toolkit @6.0.0 version for cordova users. @camengadisaputra-dev check this out.

**Comment by camengadisaputra-dev** [comment]
@neegexmayank thank you definitely check that today.

**Comment by camengadisaputra-dev** [comment]
> https://ionicframework.com/blog/updates-to-ionic-angular-toolkit/
> 
> i think this is the solution. with toolkit @6.0.0 version for cordova users. @camengadisaputra-dev check this out.

It's working thank you.
