### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project' Require stack:

### ISSUE THREAD

**Issue by llunardi** [ionic-team/angular-toolkit#469]
I keep getting this error when trying to generate a new page in Ionic - An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'
Require stack. I believe my versions of the schematics json are not in sync with the node-modules. 
![image](https://user-images.githubusercontent.com/736379/157734688-fa7caa1b-b687-4d89-ae26-5f832f6a18a9.png)

Super appreciate any and all help!

Can someone tell me in which files i need to look to make sure they are sync with the package json? Everything should be version 13.0.0 correct? @mhartington

**Comment by mhartington** [comment]
Can you please share a reproduction repo? How could I go about replicating this?

**Comment by llunardi** [comment]
Sure - sorry. I am a newbie, learning a lot still. I zipped up the repo I made today. Also, I am able to create pages within other repos I have made, just not the new one today.

**Comment by llunardi** [comment]
it won't let me attach a repo here
I tried to drag and drop it

**Comment by mhartington** [comment]
Create repo here on github and push that.

**Comment by llunardi** [comment]
ahhh that makes sense, thanks

**Comment by llunardi** [comment]
Try this - https://github.com/llunardi/ionic-conference-app - I think this is happening because I tried to create a new app using the Conference starter pack.

**Comment by mhartington** [comment]
Looks like it's an issue with the conference app.

```
  "cli": {
    "defaultCollection": "@angular-eslint/schematics"
  },
```

This should `@ionic/angular-toolkit`

Also, update to the latest version of `@ionic/angular-toolkit`, which address the `$id` error.
