### ISSUE TITLE
Data path "" should have required property 'name'.

### ISSUE THREAD

**Issue by DoctorRu** [ionic-team/angular-toolkit#47]
After install: npm i  @ionic/angular-toolkit

I got this error when I tried to use the ionic generator , (same error for modules, pages...)

```
ionic g component test2
> ng generate component test2
Schematic input does not validate against the Schema: {"styleext":"scss","inlineStyle":false,"inlineTemplate":false,"changeDetection":"Default","spec":true,"flat":false,"skipImport":false,"export":false,"entryComponent":false,"lintFix":false}
Errors:

  Data path "" should have required property 'name'.
[ERROR] Could not generate component.
```

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v11.4.0
   npm               : 5.6.0
   OS                : Linux 4.15
```

After uninstalling the toolkit, everything went back to normal.

**Comment by dwieeb** [comment]
@DoctorRu Does this happen in a new app? If not, compare the differences in the `angular.json` files.

**Comment by davl3232** [comment]
I have the same issue when running ionic generate:
```
ionic g m
? Name/path of module: components/tree
> ng generate module components/tree
Schematic input does not validate against the Schema: {"routing":false,"routingScope":"Child","spec":true,"flat":false,"commonModule":true}
Errors:

  Data path "" should have required property 'name'.
[ERROR] Could not generate module.
```
It fails for modules and components, but works for pages.

**Comment by dwieeb** [comment]
@davl3232 Also on 1.2.2? I can't seem to repro:

```
❯ ionic g m
? Name/path of module: components/tree
> ng generate module components/tree
CREATE src/app/components/tree/tree.module.ts (188 bytes)
[OK] Generated module!
```

**Comment by dwieeb** [comment]
`ng generate` uses a schematics collection to generate app features. By default (outside Ionic), the collection used is `@schematics/angular`. The Ionic starters have the following configuration in `angular.json`: https://github.com/ionic-team/starters/blob/6c824e4ef8834324648502a5cb48c89a57657a52/angular/base/angular.json#L182-L184

This setting tells the Angular CLI to use a different schematics collection. If it is not in your `angular.json`, then you're not using the schematics in `@ionic/angular-toolkit`.

**Comment by davl3232** [comment]
This works:
```
ng g c components/tree --project=wo-mobile
Your global Angular CLI version (7.2.2) is greater than your local
version (6.1.2). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
CREATE apps/wo-mobile/src/app/components/tree/tree.component.css (0 bytes)
CREATE apps/wo-mobile/src/app/components/tree/tree.component.html (23 bytes)
CREATE apps/wo-mobile/src/app/components/tree/tree.component.spec.ts (614 bytes)
CREATE apps/wo-mobile/src/app/components/tree/tree.component.ts (262 bytes)
UPDATE apps/wo-mobile/src/app/app.module.ts (3102 bytes)
```

**Comment by dwieeb** [comment]
What is `wo-mobile`? I'm not seeing that project in your `angular.json`.

**Comment by davl3232** [comment]
wo-mobile is the ionic project inside the monorepo I mentioned before.

**Comment by dwieeb** [comment]
In my monorepo, all Ionic apps and other libs share a single `angular.json` at the root of the repo, along with a single `ionic.config.json`, using [multi-app config](https://ionicframework.com/docs/cli/configuration/#multi-app-projects).

I see that you're using nrwl schematics. Depending on how your repo is setup, the Ionic CLI may be operating on the wrong `angular.json` (which would take effect when the Angular CLI runs in either the project directory or the root directory).

I'm sure there's something going wrong here, but without an example repo of the problem, I'm mostly guessing here.

**Comment by davl3232** [comment]
Hey @dwieeb, it seems I managed to fix this for the project I showed here, I just upgraded from angular 6 to 7 and did a revision of the files generated by Ionic.

I created a blank app using the latest version of Ionic cli, and compared the root files it generated with the ones I had on my ionic sub-project.

It seems I've inherited some bad configurations either from the first Ionic 4 beta or from nrwl.

Thus I made this change to my **angular.json**:

**From:**
```
{
...
  "cli": {
    "defaultCollection": "@ionic/schematics-angular"
  },
  "schematics": {
    "@ionic/schematics-angular:component": {
      "styleext": "scss"
    },
    "@ionic/schematics-angular:page": {
      "styleext": "scss"
    }
  }
}
```
**To:**
```
{
...
  "cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },
  "schematics": {
    "@ionic/angular-toolkit:component": {
      "styleext": "scss"
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    }
  }
}
```

After doing this change, I can successfully use `ionic generate` for modules, pages and components without issues.

Thank you for your help @dwieeb.

**Comment by dwieeb** [comment]
Awesome! Thanks for following up. Glad everything is working for you. 👍
