### ISSUE TITLE
Issues with Angular 14

### ISSUE THREAD

**Issue by fbl773** [ionic-team/angular-toolkit#471]
Maybe I'm just an idiot - but it looks to me like `@ionic/cordova-builders` is still dependent on `@angular-devkit/build-angular` v 13... Is there support for angular 14 coming soon? Have I done something wrong?

```
npm ERR! Found: @angular-devkit/build-angular@13.3.6                                                                                                        
npm ERR! node_modules/@angular-devkit/build-angular                                                                                                         
npm ERR!   @angular-devkit/build-angular@"^13.0.1" from @ionic/cordova-builders@6.1.0
npm ERR!   node_modules/@ionic/cordova-builders
npm ERR!     @ionic/cordova-builders@"^6.1.0" from the root project
```

**Comment by henkkelder** [comment]
To be honest: I can build with angular 14. I Just cannot run with live reload

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to consolidate this with https://github.com/ionic-team/angular-toolkit/issues/474. We are investigating and will provide more information on the linked thread when we have it.
