### ISSUE TITLE
Page schematic missing the $default field

### ISSUE THREAD

**Issue by dario-piotrowicz** [ionic-team/angular-toolkit#473]
Hi there, seems like the page schema.json is missing the requited `$default` field ([here](https://github.com/ionic-team/angular-toolkit/blob/8ff0a235e0f64b1afcab06ee1958ff6e6d474288/packages/schematics/page/schema.json#L7-L11)).

This generates some warnings in the terminal which seem to confused people.

This has come up in stackoverflow as you can see [here](https://stackoverflow.com/questions/72565789/ionic-path-option-schema-json).

**Comment by nprather** [comment]
**Here's a screenshot of the error message generated:**

![image](https://user-images.githubusercontent.com/3101108/178046823-b2eac670-bc04-4a21-8370-ee392bde15cf.png)

And here's a link to someone else that's also having the problem:
**https://stackoverflow.com/questions/72565789/ionic-path-option-schema-json**
