### ISSUE TITLE
Build error: '@ionic/angular-builders:cordova-build'

### ISSUE THREAD

**Issue by fissionessi** [ionic-team/angular-toolkit#479]
I migrated to cordova-android 11. When i try to build for android, i got below error:

Error: Could not find the '@ionic/angular-builders:cordova-build' builder's node package.
[ERROR] An error occurred while running subprocess ng.

Below is the result for 'ionic info':
<img width="731" alt="Screenshot 2022-12-01 at 12 25 40 PM" src="https://user-images.githubusercontent.com/8072858/204986098-2152cda9-7df0-4759-b0db-d4ee1d633aa3.png">

**Comment by jonz94** [comment]
Hi, it seems like it might be a typo in the `angular.json` cause this error.

I think replace `@ionic/angular-builders` with `@ionic/cordova-builders` in the `angular.json`:

```diff
        "ionic-cordova-build": {
-          "builder": "@ionic/angular-builders:cordova-build",
+          "builder": "@ionic/cordova-builders:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        }
```

should be able to fix the error.

But then, if a new error occur says:

```
Error: Could not find the '@ionic/cordova-builders:cordova-build' builder's node package.
[ERROR] An error occurred while running subprocess ng.
```

Installing the `@ionic/cordova-builders` package should be able to fix the new error.

```
npm install --save-dev @ionic/cordova-builders
```

**Comment by fissionessi** [comment]
It solves the problem. Thanks
