### ISSUE TITLE
cordova-builders with live reload do not work in combination w Angular15

### ISSUE THREAD

**Issue by henkkelder** [ionic-team/angular-toolkit#482]
The title says it all.

What worries me is that this problem exists for several months now. 
There is even a open Pull Request that will solve the problem.
But nothing happens here.

Are you abandoning Cordova support in favor of your own Capacitor? 
I sure looks like it.

**Comment by henkkelder** [comment]
Thanks, but how can I install this update? I see no new release?

**Comment by mhartington** [comment]
Because it hasn't been released yet.
