### ISSUE TITLE
bug: angular toolkit should work in angular 16

### ISSUE THREAD

**Issue by henkkelder** [ionic-team/angular-toolkit#494]
Same problem as almost a year ago.

`> ng.cmd run app:ionic-cordova-serve --host=localhost --port=8100 --platform=browser
[ng] This version of CLI is only compatible with Angular versions ^15.0.0,
[ng] but Angular version 16.1.3 was found instead.
[ng]
[ng] Please visit the link below to find instructions on how to update Angular.
[ng] https://update.angular.io/`

**Comment by henkkelder** [comment]
@liamdebeasi Could you please look into this? Would be appreciated very much.

**Comment by liamdebeasi** [comment]
Can you provide a GitHub repo that reproduces the issue?

**Comment by henkkelder** [comment]
I could, but its exactly the same problem as almost a year ago with Angular 14.

[See previous issue from year ago](https://github.com/ionic-team/angular-toolkit/issues/474)

Package.json currently `has:`
``` "@angular-devkit/architect": "^0.1500.0",
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular-devkit/core": "^15.0.3",
    "@angular-devkit/schematics": "^15.0.0",
    "@schematics/angular": "^15.0.0",
```

Since I am using Angular16 this is causing my issue.
