### ISSUE TITLE
ionic generate failing "standalone is not defined"

### ISSUE THREAD

**Issue by jwuliger** [ionic-team/angular-toolkit#509]
I have a brand-new Ionic Angular NgModule App scaffolded using the Ionic CLI.

I updated **@ionic/angular-toolkit** to version 11.0.0 and can no longer generate anything using the CLI.

**Issue:**

using ``ionic generate page/component`` results in ``standalone is not defined``

**Process:**

Use ``ionic generate component components/temp`` 

Result:

``
standalone is not defined
[ERROR] Could not generate component.
``

Is this a bug or should I have changed something? Since this update is a week old, I am having a hard time finding anything that can help.

Thanks in advance for any help.

**Comment by ragulbit** [comment]
@jwuliger I seem to have the same issue. Did you fix this issue?

**Comment by jwuliger** [comment]
> @jwuliger I seem to have the same issue. Did you fix this issue?

No unfortunately not. I have not dove into it yet. Pages seem to generate just fine, it seems to be related to the components only.

**Comment by liamdebeasi** [comment]
Hi everyone,

This was fixed in `@ionic/angular-toolkit@11.0.1`.
