### ISSUE TITLE
Support Angular 18

### ISSUE THREAD

**Issue by daze99** [ionic-team/angular-toolkit#511]
It would be nice if _@ionic/angular-toolkit_ and _@ionic/cordova-builders_ would support Angular 18.

**Comment by henkkelder** [comment]
@liamdebeasi 

Would het please be possible to add support for Angular 18?

**Comment by henkkelder** [comment]
@liamdebeasi Ah.. thats a pitty. Thanks for reacting.
Suggestions who to ask instead?

**Comment by liamdebeasi** [comment]
It would be good to provide more information on what isn't working about these packages with Angular 18. A runnable sample can help the team get a better idea of any work involved.

**Comment by henkkelder** [comment]
@mhartington 

After upgrading my project to Angular 18 and trying to run
`ionic cordova run browser -l`

I Get the following error:
`Error: export 'ɵɵInputFlags' (imported as 'i0') was not found in '@angular/core' `

npm ls @angular/core shows:
![image](https://github.com/user-attachments/assets/2d832e0f-aaad-4054-aedc-49ac94f03456)

So my conclusion is that @angular/code@18.x.x lacks an export that version 17x did have.

**Comment by henkkelder** [comment]
@mhartington @sean-perkins 

angular-toolkit / cordova-builders seems no longer maintained?

**Comment by sean-perkins** [comment]
@henkkelder Mike is no longer with Ionic and I'm no longer on the open source projects/teams at OutSystems (the company that acquired Ionic). 

This project is not actively maintained, but contributions are welcome!

**Comment by henkkelder** [comment]
@sean-perkins 

Thank you very much for your reply. 
I am disappointed to read that this project is no longer maintained. 
This means the we ionic cordova developers can no longer update to the latest Angular versions?

But should I create a PR, will anyone merge and publish the change?

**Comment by henkkelder** [comment]
@sean-perkins 

I have created a PR. Who can review and approve it?

**Comment by BraulioQueops** [comment]
@daze99 daze99 Hello. Have you found any solution that gets around this deprecation with angular 18?

**Comment by sean-perkins** [comment]
Well it took a few honest tries and updating revoked npm tokens and adjusting branch protections, but v12.1.1 is live with support for Angular 18. 

Thank you Henk for leading the development efforts to complete this 🎉

**Comment by henkkelder** [comment]
Thank you :-)Verstuurd vanaf mijn iPadOp 3 sep 2024 om 21:50 heeft Sean Perkins ***@***.***> het volgende geschreven:﻿
Well it took a few honest tries and updating revoked npm tokens and adjusting branch protections, but v12.1.1 is live with support for Angular 18.
Thank you Henk for leading the development efforts to complete this 🎉

**Comment by BraulioQueops** [comment]
Hi !!

Using these versions, the error below remains
@ionic/cordova-builders": "^11.0.0
@ionic/angular-toolkit": "^12.1.1

ionic cordova run android --device -l --host=192.168.0.180
Error: export 'ɵɵInputFlags' (imported as 'i0') was not found in '@angular/core'

**Comment by BraulioQueops** [comment]
Retracting.
I checked that 
@ionic/cordova-builders@12.0.1-testing.0 was available, and with this version everything is beautiful again.

Thank you very much to everyone on the team

**Comment by henkkelder** [comment]
@sean-perkins 

Good morning from the NL..
Could it be @ionic/cordova-builders must be published seperately from @ionic/angular-toolkit?
see https://www.npmjs.com/package/@ionic/cordova-builders

@ionic/angular-toolkit by itsself does not any functionality. Its the 2 packages inside it that do the trick.

Henk

**Comment by sean-perkins** [comment]
That package should be published under the same version now.

**Comment by henkkelder** [comment]
@sean-perkins 

I don't understand. And I also do not understand your last comment.

npmjs still only shows release 11.0.0 and npm install @ionic/cordova-builder@latest  installs version 11.0.0.
npm install @ionic/cordova-builders@12.1.1-testing.0 does install, but that doesn't seem the way to do it, does it?

**Comment by sean-perkins** [comment]
The CD workflow appeared to be successful, but doesn't look to have published the newest versions to npm. That is why the `@ionic/cordova-builders` project is still not released under the latest tag. 

I'm not familiar to why the release process was configured in this way and why it doesn't handle failures appropriately. That will require additional time/investigation to root cause.

**Comment by henkkelder** [comment]
@sean-perkins 

What can we do to fix this? @liamdebeasi @mhartington willing to help or give pointers how to solve this?
