### ISSUE TITLE
Data path "" should have required property 'name' & @ionic/angular-toolkit

### ISSUE THREAD

**Issue by OCALAB** [ionic-team/angular-toolkit#77]
Is it possible to use a custom "**webpack.config.js**" without loosing livereload option?

Using the following configuration with the command "**ionic cordova run browser --livereload**" I receive the error: [**ng] Schema validation failed with the following errors:
[ng]   Data path "" should NOT have additional properties(customWebpackConfig).**

"ionic-cordova-serve": {
          "builder": "@ionic/angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve",
            "customWebpackConfig": {
              "path": "./config/webpack.config.js"
            }
          },
          "configurations": {
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }

**Comment by dwieeb** [comment]
What is the `customWebpackConfig` option?

**Comment by OCALAB** [comment]
"cordovaBuildTarget": "app:ionic-cordova-build"

**Comment by OCALAB** [comment]
I need to use customWebpackConfig for a problem related to TypeORM (I need to switch from typeorm and typeorm/browser).

This configuration works well until I add --livereload to the serve command: ionic cordova run browser --livereload

**Comment by OCALAB** [comment]
Btw: customWebpackConfig is the way introduced in Ionic4 for using a custom webpack config during the compile process.

**Comment by dwieeb** [comment]
@OCALAB Neither Ionic nor Angular officially support providing a custom webpack config. I think you are using [@angular-builders/custom-webpack](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack).

**Comment by OCALAB** [comment]
Yes, right! The strange behaviour is that all works well without --livereload option

**Comment by OCALAB** [comment]
Finally you point me to the right direction!!

The @ionic/angular-toolkit:cordva-serve/build doesnt' supports the custom-webpack. It was quite simpler that was I tought!

Just put webpack.config.js in the project root directory (not in .config or src folder) and that it was merger in the compile/transpile task. Thanks!

**Comment by dwieeb** [comment]
Right, `customWebpackConfig` is an option of an entirely different builder, so it's not supported by this toolkit. In order to use it, you're replacing the `"builder"` option, so this code won't run.
